server:
    port: 7902
spring:
    application:
        name: guessing
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.151:3306/guessing
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    mapper-locations: classpath:mapping/*.xml #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.winter.model # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:log4j2.xml

mongo:
    username: test
    password: testpw
    database: zhangyu
    hosts: dds-uf6a8cc0dd84a8f41.mongodb.rds.aliyuncs.com,dds-uf6a8cc0dd84a8f42.mongodb.rds.aliyuncs.com
    port: 3717
    replicaSet: mgset-4453197

gunqiu:
    vendorIdValue: 1521
    vendorAppIdValue: 1001
    secretKey: test001